# Generated by Django 5.1.2 on 2024-10-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='autochat',
            options={'verbose_name_plural': 'สคริปต์แชท'},
        ),
    ]
