# Generated by Django 5.1.2 on 2024-10-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0002_trainingstatus_alter_autochat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingstatus',
            name='progress',
            field=models.FloatField(),
        ),
    ]
