# Generated by Django 5.1.2 on 2024-10-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0003_alter_trainingstatus_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingstatus',
            name='progress',
            field=models.IntegerField(default=-1),
        ),
    ]
