# Generated by Django 5.1.2 on 2024-10-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0005_delete_trainingstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('user_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('line_uid', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'การแจ้งเตือน',
            },
        ),
    ]
