# Generated by Django 5.1.2 on 2024-10-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auto-chats/'),
        ),
    ]
