# Generated by Django 5.1.2 on 2024-10-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0009_autochat_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'แท็ก'},
        ),
    ]
