# Generated by Django 5.1.2 on 2024-10-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0010_alter_tag_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'บันทึกแชท',
            },
        ),
    ]
