# Generated by Django 5.1.2 on 2024-10-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0011_chatrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.TextField()),
                ('fine_tuned_model', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('in_use', models.BooleanField(default=False)),
            ],
        ),
    ]
